---
- name: Ensure Prometheus user and group exist
  ansible.builtin.user:
    name: prometheus
    comment: "Prometheus service account"
    system: yes
    shell: /sbin/nologin
    createhome: no

- name: Ensure Prometheus directory exists and is owned by Prometheus user
  ansible.builtin.file:
    path: /opt/prometheus
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0755

- name: Download and extract Prometheus
  unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v2.35.0/prometheus-2.35.0.linux-arm64.tar.gz"
    dest: "/opt/prometheus/"
    remote_src: true
    creates: "/opt/prometheus/prometheus"

- name: Configure Prometheus
  template:
    src: prometheus.yml.j2
    dest: "/opt/prometheus/prometheus.yml"

- name: Copy Prometheus systemd service file
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify:
    - reload systemd

- name: Ensure Prometheus data directory exists
  ansible.builtin.file:
    path: /opt/prometheus/data
    state: directory
    owner: prometheus
    group: prometheus

- name: Ensure Prometheus is running
  systemd:
    name: prometheus
    state: started
    enabled: true
    daemon_reload: yes
