---
- name: Add Grafana GPG key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana repository
  ansible.builtin.apt_repository:
    repo: 'deb https://packages.grafana.com/oss/deb stable main'
    state: present
    update_cache: yes

- name: Install Grafana
  ansible.builtin.apt:
    name: grafana
    state: present
    update_cache: yes

- name: Ensure Grafana is running
  ansible.builtin.systemd:
    name: grafana-server
    state: started
    enabled: yes
