---
- name: Enable Cgroup Memory on Raspberry Pi
  hosts: myhosts:!control
  become: yes
  tasks:
    - name: Check if cgroup settings are present in /boot/firmware/nobtcmd.txt
      ansible.builtin.shell: grep -q 'cgroup_memory=1 cgroup_enable=memory' /boot/firmware/nobtcmd.txt
      register: grep_cgroup
      failed_when: false
      changed_when: false

    - name: Append cgroup settings to /boot/firmware/nobtcmd.txt
      ansible.builtin.lineinfile:
        path: /boot/firmware/nobtcmd.txt
        line: "{{ item }}"
        create: no
      with_items:
        - " cgroup_memory=1"
        - " cgroup_enable=memory"
      when: grep_cgroup.rc != 0

    - name: Reboot the system
      ansible.builtin.reboot:
      when: grep_cgroup.rc != 0
